# ビルドステージ（Viteでdistを作る）
FROM node:18 AS builder
WORKDIR /app
COPY ./frontend ./
RUN npm install && npm run build

# 実行ステージ（Nginxサーバー）
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
