
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloudnote
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
    # データ永続化用のボリュームを追加
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - cloudnet

  spring:
    container_name: spring-1
    build:
      context: ./cloudnote-backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cloudnote
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - cloudnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - spring
    ports:
      - "5173:5173"
    networks:
      - cloudnet

# データ永続化用の named volume 定義
volumes:
  dbdata:

# 各サービスをつなぐカスタムネットワーク
networks:
  cloudnet:
    driver: bridge
